[package]
name = "tezos_interop_callback"
version = "1.3.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
ocaml-interop = { version = "0.7.2", features = ["without-ocamlopt"] }
# local dependencies
tezos-sys = { path = "../sys" }
tezos_context = { path = "../context" }
